# Generated by Django 3.0.8 on 2020-12-13 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('home_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('who_referred_you', models.CharField(max_length=255, verbose_name='Who referred you to us?')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_hours_desired', models.PositiveIntegerField()),
                ('desired_pay_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Asking rate of pay')),
                ('pool_preference', models.CharField(max_length=255)),
                ('subdivision', models.CharField(max_length=255, verbose_name='Which subdivision do you live in or nearby')),
                ('work_authorization', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None)),
                ('charged_or_arrested_resolved', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None)),
                ('charged_or_arrested_not_resolved', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None)),
                ('contract_employment_agreement', models.BooleanField()),
                ('electronic_signature', models.CharField(max_length=255, verbose_name='Your name')),
                ('is_hired', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Accepted for hire')),
                ('application_under_review', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('minimum_age', models.PositiveIntegerField(default=15, verbose_name='Minimum age requirement')),
                ('lifeguard_required', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is lifeguard certification required for this position?')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w4', models.FileField(upload_to='')),
                ('i9', models.FileField(upload_to='')),
                ('workers_comp', models.FileField(upload_to='')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_employer', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField(verbose_name='Starting date of employement')),
                ('end_date', models.DateField(verbose_name='Ending date of employement?')),
                ('reason_for_leaving', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='Name of school')),
                ('grade_year', models.CharField(max_length=255, verbose_name='What grade/year are you')),
                ('attending_college', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Will you attend college this fall?')),
                ('date_leaving_to_college', models.DateField(blank=True, null=True, verbose_name='If leaving to college in the Fall when will you leave?')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='applied_positions',
            field=models.ManyToManyField(to='employee.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Transportation'),
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.FileField(null=True, upload_to='')),
                ('social_security_card', models.FileField(null=True, upload_to='')),
                ('social_security_number', models.CharField(max_length=10, null=True)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('w4', models.FileField(null=True, upload_to='')),
                ('i9', models.FileField(null=True, upload_to='')),
                ('workers_comp', models.FileField(null=True, upload_to='')),
                ('vaccination_record', models.FileField(blank=True, null=True, upload_to='')),
                ('hepB_waiver_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('banking_name', models.CharField(max_length=255, null=True)),
                ('account_type', models.CharField(choices=[('S', 'Savings Account'), ('C', 'Checkings Account')], default=None, max_length=1, null=True)),
                ('account_number', models.CharField(max_length=255, null=True)),
                ('savings_number', models.CharField(max_length=255, null=True)),
                ('email_address', models.EmailField(max_length=255, null=True)),
                ('auth_signature', models.CharField(max_length=255, null=True)),
                ('awknowledgement_form_signature', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
