# Generated by Django 3.0.8 on 2020-12-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
