# Generated by Django 3.0.8 on 2020-12-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_checklist_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='complete',
        ),
    ]
