# Generated by Django 3.0.8 on 2021-01-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_checklist_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='description',
        ),
    ]
