# Generated by Django 3.0.8 on 2021-01-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210114_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='savings_number',
            new_name='router_number',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='photo_id',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Photo Identification'),
        ),
    ]
