# Generated by Django 3.0.8 on 2021-01-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210119_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='employee_handbook',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='i9',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='w4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='workers_comp',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
