# Generated by Django 3.0.8 on 2021-01-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210119_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='completed_orientation',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
