# Generated by Django 3.0.8 on 2021-02-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20210216_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='i9',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='social_security_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='vaccination_record',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='w4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='workers_comp',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
