# Generated by Django 3.0.8 on 2020-12-13 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lifeguard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already_certified', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='Are you a certified lifeguard?')),
                ('wants_to_work_for_company', models.BooleanField(choices=[(True, 'Yes (I want the discounted employee rate)'), (False, 'No, I will be working elsewhere (NOT eligible for discount)')], default=None, verbose_name='Do you plan to work for Gulf Coast Aquatics?')),
                ('payment_agreement', models.BooleanField()),
                ('payment_agreement_signature', models.CharField(max_length=255)),
                ('no_refunds_agreement', models.BooleanField()),
                ('electronic_signature', models.CharField(max_length=255, verbose_name='Electronic signature')),
                ('last_certified', models.DateField(null=True)),
                ('certification', models.FileField(null=True, upload_to='')),
                ('online_portion_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LifeguardClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('employee_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lifeguard_certified_required', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Do the students need to be lifeguard certified to take this class?')),
                ('is_review', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is this class a review for expiring lifeguard certificates?')),
                ('students', models.ManyToManyField(through='lifeguard.Enroll', to='lifeguard.Lifeguard')),
            ],
        ),
        migrations.AddField(
            model_name='enroll',
            name='lifeguard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeguard.Lifeguard'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='lifeguard_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeguard.LifeguardClass'),
        ),
    ]
