# Generated by Django 3.0.8 on 2021-01-14 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifeguard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeguardClassSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lifeguard_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifeguard.LifeguardClass')),
            ],
        ),
    ]
