# Generated by Django 3.0.8 on 2021-02-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeguard', '0006_auto_20210125_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeguardclass',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lifeguardclass',
            name='max_enrollment',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='lifeguardclass',
            name='min_enrollment',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
