# Generated by Django 3.0.8 on 2021-02-15 23:28

from django.db import migrations, models
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('lifeguard', '0007_auto_20210208_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeguard',
            name='certification',
            field=models.FileField(null=True, storage=storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
