# Generated by Django 3.0.8 on 2021-02-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeguard', '0008_auto_20210215_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeguard',
            name='certification',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
